# 02 - Data Preprocessing dengan Scikit Learn

## Sample Data
- Dataset ini bisa kita pandang sebagai dataset feature.
- Dan dataset ini terbagi menjadi 3 feature.

In [1]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5], 
                        [-1.5, 2.4, 3.5], 
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

- Untuk menampilkan dimensi dari dataset.

In [2]:
sample_data.shape

(4, 3)

## Binarisation
- Tujuan utamanya dari teknik ini yaitu untuk menghasilkan suatu data yang terdiri dari 2 nilai numerik saja yaitu 0 dan 1.

In [5]:
sample_data # menampilkan dataset yang sudah dibentuk sebelumnya.

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [4]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

- hasil dari proses binarisation ini adalah suatu dataset yang hanya terdiri dua nilai yaitu 1 dan 0 dimana batasannya ditentukan oleh nilai threshold.
- arti dari nilai threshold (0,5) yaitu setiap nilai yang lebih kecil atau sama dengan 0,5 maka akan akan dikonversikan menjadi 0 dan sedangkan nilai yang lebih besar akan dikonversikan menjadi nilai 1.

## Scaling
- Tujuan utama dari Scaling ini adalah untuk menghasilkan data numerik yang berada dalam skala tertentu.

In [6]:
sample_data # menampilkan dataset yang sudah dibentuk sebelumnya.

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [7]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [8]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

## L1 Normalisation : Least Absolut Deviations

In [ ]:
sample_data

In [ ]:
l1_normalised_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data

## L2 Normalisation : Least Squares

In [ ]:
sample_data

In [ ]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data